### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Z-fly** [clinux-co/x_google_installer#2]
使用加速代理下载
http://toolwa.com/github/

https://github3.mk-proxy.ml/-----https://github.com/clinux-co/x_google_installer/releases/download/s210214063/com.google.android.gms_21.02.14_.110306-352619232.-210214063_minAPI27.armeabi-v7a.320dpi._apkmirror.com.apk

https://github3.mk-proxy.ml/-----https://github.com/clinux-co/x_google_installer/releases/download/gp_82382410/com.android.vending_23.8.24-21_0_PR_354192728-82382410_minAPI21.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.apk

**Comment by Z-fly** [comment]
@xkeyC

**Comment by xkeyC** [comment]
我觉得没这个必要，使用 GMS 的都有自己的加速渠道，我没必要冒着一些风险用第三方。
如果你有其他意见，欢迎继续留言。
